# Generated by Django 4.1.7 on 2023-04-13 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_placedorders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlacedOrders',
        ),
    ]
